appointment/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.main_app.urls', namespace = 'main')),
    url(r'^appointment/', include('apps.appointment_app.urls', namespace = 'promise')),
]

apps/appointment_app/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.add, name='create'),
    url(r'^(?P<task_id>\d+)/show$', views.showUpdate, name='show_update'),
    url(r'^(?P<task_id>\d+)/udpate$', views.update, name='update'),
    url(r'^(?P<task_id>\d+)$', views.showDelete, name='show_delete'),
    url(r'^(?P<task_id>\d+)/delete$', views.delete, name='delete')


]

apps/main_app/urls.py
from django.conf.urls import url,include
import views

urlpatterns = [
    url(r'^$', views.index, name='mainindex'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$',views.registration, name='register'),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^success$', views.success, name='success' ),
]

apps/appointment_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..main_app.models import User
from datetime import datetime, timedelta
import re  # import python regex module
# Create your models here.

DATE_REGEX = re.compile(r'^((?:19|20)\d\d)[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$')
TIME_REGEX = re.compile(r'^(([01]\d|2[0-3]):([0-5]\d)|24:00)$')


class AppointmentManager(models.Manager):

    def validate(self, data):
        print data['date']
        errors = []
        print "@@@@@@@@@@@@@@@@@@@@@@@ datetime.today"
        # datetime.today()
        # strdatetime =  data['date'] + data['time']
        # print "@@@@@@@@@@@@@@@@@@@@@@@ strdatetime"

        # print strdatetime
        # date = datetime.strptime(strdatetime, "%Y-%m-%d")
        # time = datetime.strptime(strdatetime, "%H:%M")
        # datetime = datetime.strptime(strdatetime, "%Y-%m-%d%H:%M")
        # print "@@@@@@@@@@@@@@@@@@@@@@@ x"
        # print x
        # print type(u'2014-03-06T04:38:51Z') is types.UnicodeType

        if len(data['date']) < 1:
            errors.append(" Date is empty")
        if not DATE_REGEX.match(data['date']):
            errors.append("date is not valid")
        if len(data['time']) < 1:
            errors.append("Time is empty")
        if not TIME_REGEX.match(data['time']):
            errors.append("Time is not valid")
        if len(data['task']) < 1:
            errors.append("Task info is empty")
        if len(data['status']) < 1:
            errors.append("Missing status")

        if len(errors) == 0:
            strdatetime =  data['date'] + " " + data['time']
            print strdatetime
            # d == datetime.combine(d.date(), d.timetz())
            datetime_object = datetime.strptime(strdatetime, '%Y-%m-%d %H:%M')
            print datetime_object
            # d == datetime.combine(d.date(), d.timetz())
            # then = datetime.strptime(u'04:38:51Z', "%H:%M:%SZ")
            # print then
            # d = datetime.combine(data['date'], data['time'])
            # print d
            # d = datetime.strptime(strdatetime, "%Y-%m-%dT%H:%M:%SZ")
            # print "@@@@@@@@@@@@@@@@@@@@@@@"
            # print d
            # print "@@@@@@@@@@@@@@@@@@@@@@@"
            if datetime_object < datetime.utcnow()-timedelta(hours=5):
                errors.append("appointment must be the future.")

        if len(errors):
            return {'status':True, 'errors':errors}
        else:
            return {'status':False, 'datetime':datetime_object}
    def currentTasks(self, user_id):
        today = datetime.utcnow()
        tasks =  self.filter(user_id=user_id, taskdatetime__year=today.year,taskdatetime__month=today.month, taskdatetime__day=today.day).order_by('-taskdatetime')
        return tasks

    def futureTasks(self, user_id):
        today = datetime.utcnow()
        tasks =  self.filter(user_id=user_id).exclude(taskdatetime__year=today.year,taskdatetime__month=today.month, taskdatetime__day=today.day).order_by('-taskdatetime')
        return tasks

    def getTask(self, task_id):
        user_task = self.get(id=task_id)
        return user_task

    def addTask(self,user_id, postData):
        response = self.validate(postData)
        # print response
        if response['status'] :
            return response
        else :
            try  :
                date_time = response['datetime']
                user = User.objects.get(id=user_id)
                task = self.create(task=postData['task'], user=user, taskdatetime=date_time,  status=postData['status'])
                print task
            except:
                response['status'] = True
                response['errors'] = ["Duplicate error."]
            return response

    def updateTask(self,user_id, task_id, postData):
        response = self.validate(postData)
        if response['status'] :
            return response
        else :
            date_time = response['datetime']
            user = User.objects.get(id=user_id)
            try :
                user_task = self.get(id=task_id)
                user_task.task=postData['task']
                user_task.user=user
                user_task.taskdatetime=date_time
                user_task.status=postData['status']
                user_task.save()
            except :
                response['status'] = True
                response['errors'] = ["something wrong, fix it!."]
            return response

    def deleteTask(self, task_id):
        user_task = self.get(id=task_id)
        user_task.delete()
        return

class Appointment(models.Model):
    user = models.ForeignKey(User, related_name='task')
    status = models.CharField(max_length=255)
    task = models.CharField(max_length=500)
    taskdatetime = models.DateTimeField(auto_now=False, auto_now_add=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AppointmentManager()

apps/appointment_app/views.py
from django.shortcuts import render ,redirect
from models import Appointment
from django.contrib import messages
from datetime import datetime

# Create your views here.
def index(request):
    print Appointment.objects.futureTasks(request.session['user_id'])
    # print Appointment.objects.futureTasks(request.session['user_id'])[1]
    # print Appointment.objects.futureTasks(request.session['user_id'])[1].user.id
    # print Appointment.objects.futureTasks(request.session['user_id'])[2].user.id
    # print Appointment.objects.futureTasks(request.session['user_id'])[3].user.id
    # print Appointment.objects.futureTasks(request.session['user_id'])[4].user.id
    # print Appointment.objects.futureTasks(request.session['user_id'])[5].user.id
    # print Appointment.objects.futureTasks(request.session['user_id'])[6].user.id
    print request.session['user_id']
    try:
        context = {
            'name': request.session['user'],
            'status': request.session['user_status'],
            'task_date':datetime.now(),
            'current_appointments': Appointment.objects.currentTasks(request.session['user_id']),
            'other_appointments':Appointment.objects.futureTasks(request.session['user_id'])
            }
        return render(request, 'appointment_app/index.html', context)
    except KeyError:
            return redirect('main:mainindex')
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

def add(request):
    if request.method == 'POST':
        try:
            context = {
                'name': request.session['user'],
                'status': request.session['user_status'],
                }
            # print context
            response = Appointment.objects.addTask(request.session['user_id'], request.POST)
            print response
            if response['status'] :
                for error in response['errors']:
                    messages.error(request, error)
            return redirect('promise:index')
        except KeyError:
                return redirect('main:mainindex')
############################################################
def showUpdate(request, task_id):

    try:
        context = {
            'name': request.session['user'],
            'status': request.session['user_status'],
            'appointment':Appointment.objects.getTask(task_id)
            }
        # print context
        return render( request, 'appointment_app/update.html', context)
    except KeyError:
            return redirect('main:mainindex')
###############################################################
def showDelete(request, task_id):
    try:
        context = {
            'name': request.session['user'],
            'status': request.session['user_status'],
            'appointment':Appointment.objects.getTask(task_id)
            }
        # print context
        return render( request, 'appointment_app/delete.html', context)
    except KeyError:
            return redirect('main:mainindex')
######################################################################
def update(request, task_id):
   if request.method == 'POST':
        try:
            context = {
                'name': request.session['user'],
                'status': request.session['user_status'],
                }
            print context
            response = Appointment.objects.updateTask(request.session['user_id'], task_id, request.POST)
            print response
            if response['status'] :
                for error in response['errors']:
                    messages.error(request, error)
            return redirect('promise:index')
        except KeyError:
                return redirect('main:mainindex')
#######################################################################
def delete(request, task_id):
    if request.method == 'POST':
        try:
            context = {
                'name': request.session['user'],
                'status': request.session['user_status'],
                }
            response = Appointment.objects.deleteTask(task_id)
            return redirect('promise:index')
        except KeyError:
            return redirect('main:mainindex')

apps/appointment_app/templates/appointment_app/delete.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>delete</title>

        {% load static %}
        <style>
        p{
          font-size: 20px;
          margin-left: 30px;
        }
        label {
               font-size: 20px;
               font-family: "Times New Roman", Georgia, Serif;
               margin:20px;
               margin-left:25px;
               vertical-align:top;
        }
        form input {
            font-size: 20px;
            margin-left:40px;
            margin-bottom:30px;
        }
        form input[type=submit] {
            font-size: 15px;
            margin-left:200px;
            margin-top: 20px;
            height:40px;
            width:80px;
            color:black;
            background-color:skyblue;
        }

        </style>

    </head>
    <body>
        <div id="container">
           <form  action="{% url 'promise:delete'  task_id=appointment.id %}"  method="post">
                {% csrf_token %}
                <h4>Delete Appoint</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}

                <p>Task :   {{ appointment.task }}</p>
                <p>Status :   {{ appointment.status }}</p>
                <p>Date :   {{ appointment.taskdatetime|date:"m/d/Y" }}</p>
                <p>Time :   {{ appointment.taskdatetime|date:"H:i" }}</p>

                <input type="submit" name="add" value="Delete"/><br>
            </form>
            <a href="{% url 'promise:index' %}">Appointment Status</a>   |      <a href="{% url 'main:logout' %}">Logout</a>

        </div>
    </body>
</html>

apps/appointment_app/templates/appointment_app/index.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Appointment</title>

        {% load static %}
        <style>
            h2{
              font-size: 25px;
            }
            p{
                font-family: "Times New Roman", Georgia, Serif;
                color:blue;
                font-size: 20px;
             }
             table, th, td {
                border: 1px solid black;
                padding: 7px;
            }
            .container{
              display: inline-block;
              margin-left: 25px;
            }
            .add_logout{
               font-size: 20px;
               margin-left: 30px;
               margin-top: 30px;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <h2>Hello,  {{ name }}!</h2>


            <div id="my_appoitments">
                <p>Here are your appointments lists</p>
                <p>Today is  {{ task_date|date:"D d M Y" }} </p>
                <table>
                    <th>Task</th>
                    <th>Time</th>
                    <th>Status</th>
                    <th>Action</th>
                    {% for appointment in current_appointments %}
                        <tr>
                            <td>({{appointment.user.name}}) {{appointment.task}}</td>
                            <td>{{appointment.taskdatetime|date:"H:i"}}</td>
                            <td>{{appointment.status}}</td>
                            {% if appointment.status == "Pending" %}
                                <td>
                                    <a href="{% url 'promise:show_update' task_id=appointment.id %}" >Edit</a>
                                    <a href="{% url 'promise:show_delete' task_id=appointment.id %}">Delete</a>
                                </td>


                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <br>
            <div id="other_appointments">
                <p>Your other appointments</p>
                <table>
                    <th>Task</th>
                    <th>Date</th>
                    <th>Time</th>
                    {% for appointment in other_appointments %}
                        <tr>
                            <td>({{appointment.user.name}}) {{appointment.task}}</td>
                            <td>{{ appointment.taskdatetime|date:"D d M Y" }}</td>
                            <td>{{appointment.taskdatetime|date:"H:i"}}</td>

                        </tr>
                    {% endfor %}
                </table>
            </div>
          </div>
          <div class="container">
            <div class="add_logout">
                  <form  action="{% url 'promise:create' %}"  method="post">
                      {% csrf_token %}
                      <h4>Add appointment</h4>
                        {% for message in messages %}
                          <p>{{ message }}</p>
                        {% endfor %}
                      <label>Date: </label><input type="date" value = "" name="date" placeHolder="MM/DD/YYYY"/> (use calendar)<br>
                      <label>Time: </label><input type="text" value = "10:30" name="time" placeHolder="HH:MM"/> (like-21:30(Europe/MilitaryTime)<br>
                      <label>Tasks: </label><input type="text" name="task"/><br>
                      <input type="hidden" name="status" value="Pending"/><br>
                      <input type="submit" name="add" value="Add"/><br>
                  </form>

                    <form  action="{% url 'main:logout' %}"  method="post">
                        {% csrf_token %}
                        <input type="submit" value="logout"/>
                    </form>
              </div>
          </div>
    </body>
</html>

apps/appointment_app/templates/appointment_app/show.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content=""/>
        <title>show</title>
    </body>
</html>

apps/appointment_app/templates/appointment_app/update.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>update</title>

        {% load static %}
        <style>
            label {
                   font-size: 20px;
                   font-family: "Times New Roman", Georgia, Serif;
                   margin:20px;
                   margin-left:25px;
                   vertical-align:top;
            }
            form input {
                font-size: 20px;
                margin-left:40px;
                margin-bottom:30px;
            }
            form input[type=submit] {
                font-size: 15px;
                margin-left:200px;
                margin-top: 20px;
                height:40px;
                width:80px;
                color:black;
                background-color:skyblue;
            }



        </style>

    </head>
    <body>
        <div id="container">
           <form  action="{% url 'promise:update'  task_id=appointment.id %}"  method="post">
                {% csrf_token %}
                <h4>Update Appointment</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>Tasks:</label><input type="text" name="task"/ value='{{appointment.task}}'><br>
                <label>Status:     </label>
                <select name="status" value='{{appointment.status}}'>
                  <option value="Pending">Pending</option>
                  <option value="Missed">Missed</option>
                  <option value="Done">Done</option>
                </select><br><br>
                <label>Date:</label><input type="date" name="date" placeHolder="MM/DD/YYYY"  value='{{appointment.taskdatetime|date:"m/d/Y"}}'/><br>
                <label>Time:</label><input type="text" name="time" placeHolder="HH:MM" value='{{appointment.taskdatetime|date:"H:i"}}'/><br>
                <input type="submit" name="add" value="Update"/><br>
            </form>

             <a href="{% url 'promise:index' %}">Appointment Status</a>   |      <a href="{% url 'main:logout' %}">Logout</a>
        </div>
    </body>
</html>