appointment/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.main_app.urls', namespace = 'main')),
    url(r'^appointment/', include('apps.appointment_app.urls', namespace = 'promise')),
]

apps/main_app/urls.py
from django.conf.urls import url,include
import views

urlpatterns = [
    url(r'^$', views.index, name='mainindex'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$',views.registration, name='register'),
    url(r'^logout$', views.logout, name='logout' ),
    url(r'^success$', views.success, name='success' ),
]

apps/main_app/models.py
from __future__ import unicode_literals
from django.db import models
import re  # import python regex module
import bcrypt


EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
DATE_REGEX = re.compile(r'^((?:19|20)\d\d)[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$')
class UserManager(models.Manager):

        def registration(self, data):
            errors = []
            print data['date_birth']
            if len(data['name']) < 3:
                errors.append("first name is empty or needs more 2 chars")
            if len(data['email']) < 3:
                errors.append(" no email?")
            if not EMAIL_REGEX.match(data['email']):
                errors.append(" email is not valid")
            if not DATE_REGEX.match(data['date_birth']):
                errors.append(" date is not valid")
            if len(data['password']) < 8:
                errors.append("password is empty  or needs more 8 chars")
            if len(data['confirm_ps']) < 8:
                errors.append("confirm password is empty or needs more than 8 characters")

            if data['confirm_ps'] != data['password'] :
                errors.append("password and confirm password are not same")
            if len(errors) == 0:
                user = self.filter(email=data['email'])
                if user :
                    errors.append("user alraedy exist")

            response = {}

            if len(errors) > 0:
                response['status'] = False
                response['errors'] = errors
            else :
                hashed_password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
                user = self.create(name=data['name'],

                            email=data['email'],
                            password=hashed_password)
                response['status'] = True
                response['user'] = user

            return response

        def login(self, data):

            response = {}
            errors = []

            if len(data['email']) < 1:
                errors.append(" email is empty")
            if not EMAIL_REGEX.match(data['email']):
                errors.append(" email is not valid")
            if len(data['password']) < 8:
                errors.append("password is empty  or needs more 8 chars")

            if len(errors) == 0:
                user = self.filter(email=data['email'])
                if user :
                    if bcrypt.checkpw(data['password'].encode(), user[0].password.encode()):
                        response['status'] = True
                        response['user'] = user[0]
                    else :
                        errors.append("Invalid password try again")
                        response['status'] = False
                        response['errors'] = errors
                else :
                    errors.append("Invalid user try again")
                    response['status'] = False
                    response['errors'] = errors
            else :
                response['status'] = False
                response['errors'] = errors
            return response

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=34)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=256)
    created_at =  models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/main_app/views.py
from django.shortcuts import render, redirect,HttpResponse
from models import User

from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, 'main_app/index.html')

def registration(request):
    if request.method == "POST":
        response_from_model = User.objects.registration(request.POST)
        if  response_from_model['status']:
            request.session['user_id'] = response_from_model['user'].id
            request.session['user'] = response_from_model['user'].name
            return redirect('main:success')
        else:
            for error in response_from_model['errors']:
                messages.error(request, error)
    return redirect('main:mainindex')

def login(request):

    if request.method == 'POST':
        response_from_model = User.objects.login(request.POST)
        if  response_from_model['status']:
            request.session['user_id'] = response_from_model['user'].id
            request.session['user'] = response_from_model['user'].name
            return redirect('main:success')
        else:
            for error in response_from_model['errors']:
                messages.error(request, error)
    return redirect('main:mainindex')

def logout(request):

    if request.method == "POST":
        if 'user_id' in request.session:
           request.session.pop('user_id')
           request.session.pop('user')
    request.session['user_status'] = 'logged out'
    return redirect("main:mainindex" )

def success(request):
    if 'user_id' in request.session:
        request.session['user_status']  = 'logged in'
        return redirect('promise:index')
    else :
        return redirect('main' )

apps/main_app/templates/main_app/index.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content=""/>
        <title>Appointment</title>

        {% load static %}
        <style>
            .container{
              display: inline-block;
              vertical-align: top;
              border: 1px solid black;
              margin-left: 20px;
              padding: 5px;
            }
            p{
              font-size: 25px;
              font-style: normal;
              color: red;
            }
            label {
                   font-family: "Times New Roman", Georgia, Serif;
                   vertical-align:top;
                   display:inline-block;
                   width:170px;
                   text-align:right;
            }
            form input {
                margin-bottom:20px;
                margin-left:5px;
            }
            form input[type=submit] {
                margin-left:200px;
                width:90px;
                color:black;
                background-color:skyblue;
            }
        </style>

    </head>
    <body>
        <div class="container">
            <form  action="{% url 'main:register' %}"  method="post">
                {% csrf_token %}
                <h4> REGISTRATION</h4>
                  {% for message in messages %}
                    <p>{{ message }}</p>
                  {% endfor %}
                <label>Name:</label><input type="text" name="name"/><br>
                <label>Email:</label><input type="email" name="email"/><br>
                <label>Password:</label><input type="password" name="password"/><br>
                <label>Confirm Password:</label><input type="password" name="confirm_ps"/><br>
                <label>Date Birth:</label><input type="date" name="date_birth" /> (try calendar!)<br>
                <input type="submit" name="resgiter" value="Resgiter"/><br>
            </form>
        </div>
        <div class="container">
            <form  action="{% url 'main:login' %}"  method="post">
                {% csrf_token %}
                <h3>LOGIN</h3>
                <label>Email:</label><input type="email" name="email"/><br>
                <label>Password:</label><input type="password" name="password"/><br>
                <input type="submit" name="login" value="Login"/><br>
            </form>
        </div>


    </body>
</html>

apps/main_app/templates/main_app/success.html
<!DOCTYPE hmtl>
<html>
    <head>
        <meta charset="utf8" />
        <meta name="descripition" content="Learning about Django"/>
        <title>Courses</title>

        {% load static %}
        <link rel="stylesheet" href={% static "first_app/css/index.css"  %}></link>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src={% static "first_app/js/index.js"  %}></script>
        <style>
            p{
                color:green;
             }
             table, th, td {
                border: 1px solid black;
                padding: 15px;
            }
        </style>

    </head>
    <body>
        <div id="container">
            <h2>Sucess! Welcome, {{first_name}}!</h2>
            <p><small>Succesfully {{status}}</small></p>

            <form  action="{% url 'courses:create_user' %}"  method="post">
                {% csrf_token %}
                <select name="user_id">
                    {% for user in users %}
                    <option value='{{user.id}}'>{{user.first_name}}_{{user.last_name}}</option>'
                    {% endfor %}
                </select>
                 <select name="course_id">
                    {% for course in courses %}
                    <option value='{{course.id}}'>{{course.course_name}}</option>
                    {% endfor %}
                </select>

                <input type="submit" value="Add User To Course"/>
            </form>

            <div id="courses_user_distro">
                <table>
                    <th>Course</th>
                    <th>Title</th>
                    <th>Numbero of Users</th>
                    {% for course in courses %}
                        <tr>
                            <td>{{course.id}}</td>
                            <td>{{course.course_name}}</td>
                            <td>{{course.users.count}}</td>
                        </tr>
                    {% endfor %}
                </table>

            </div>
            <br>
            <form  action="/logout"  method="post">
                {% csrf_token %}
                <input type="submit" value="logout"/>
            </form>

        </div>
    </body>
</html>